//
// Generated file, do not edit! Created by nedtool 4.6 from Nack.msg.
//

#ifndef _NACK_M_H_
#define _NACK_M_H_

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0406
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Class generated from <tt>Nack.msg:17</tt> by nedtool.
 * <pre>
 * packet Nack
 * {
 *     int status;
 *     int num;
 *     int seq[20];
 * }
 * </pre>
 */
class Nack : public ::cPacket
{
  protected:
    int status_var;
    int num_var;
    int seq_var[20];

  private:
    void copy(const Nack& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const Nack&);

  public:
    Nack(const char *name=NULL, int kind=0);
    Nack(const Nack& other);
    virtual ~Nack();
    Nack& operator=(const Nack& other);
    virtual Nack *dup() const {return new Nack(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual int getStatus() const;
    virtual void setStatus(int status);
    virtual int getNum() const;
    virtual void setNum(int num);
    virtual unsigned int getSeqArraySize() const;
    virtual int getSeq(unsigned int k) const;
    virtual void setSeq(unsigned int k, int seq);
};

inline void doPacking(cCommBuffer *b, Nack& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, Nack& obj) {obj.parsimUnpack(b);}


#endif // ifndef _NACK_M_H_

